name: Deploy application
 
on:
  push:
    branches: [ master ]
 
jobs:
  push_to_registry:
    name: Push Docker image to Dockerhub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: arifjmamun/webserver
          tag_with_ref: true
  # deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy Webserver
  #       uses: appleboy/ssh-action@v0.1.2
  #       with:
  #         host: ${{secrets.SSH_HOST}}
  #         username: ${{ secrets.SSH_USERNAME }}
  #         key: ${{ secrets.SSH_PRIVATE_KEY }}
  #         script: |
  #           cd /var/www/webserver
  #           sudo git pull
  #           export NVM_DIR="$HOME/.nvm"
  #           [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
  #           nvm use stable
  #           node -v
  #           npm -v
  #           npm install
  #           pm2 startOrReload webserver.config.js